language: php

php:
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install

script:
  - vendor/bin/psalm
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml
  - vendor/bin/infection

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
