language: php

php:
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install

script:
  - vendor/bin/psalm
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/infection
